### ISSUE TITLE
mistake when using baseline model

### ISSUE THREAD

**Issue by tongjinle123** [baidu/knowledge-driven-dialogue#2]
there is a mistake when I ran the best.model 
----> 1 t.load('models/best.model')

~/miniconda3/envs/torch1/lib/python3.6/site-packages/torch/serialization.py in load(f, map_location, pickle_module)
    365         f = open(f, 'rb')
    366     try:
--> 367         return _load(f, map_location, pickle_module)
    368     finally:
    369         if new_fd:

~/miniconda3/envs/torch1/lib/python3.6/site-packages/torch/serialization.py in _load(f, map_location, pickle_module)
    526             f.seek(0)
    527
--> 528     magic_number = pickle_module.load(f)
    529     if magic_number != MAGIC_NUMBER:
    530         raise RuntimeError("Invalid magic number; corrupt file?")

EOFError: Ran out of input

**Comment by imguozhen** [comment]
The best.model file is just an empty file to show the structure of the document. You can train your own model by running run_train.sh, and then evaluate it by running run_test.sh.
