### ISSUE TITLE
how can i creat demo.train when i have train.txt?

### ISSUE THREAD

**Issue by luhua-rain** [baidu/knowledge-driven-dialogue#3]
The READEME dose not tell us how to creat demo.train?

**Comment by imguozhen** [comment]
step 1: firstly have to convert session data to sample data by ./tools/convert_session_to_sample.py step 2: convert sample data to text data required by the model by ./tools/convert_conversation_corpus_to_model_text.py

The script run_train.sh/run_test.sh shows all the processes including data processing and model training/testing. Be sure to read it carefully and follow it.

**Comment by basketballandlearn** [comment]
Thank you for your reply！！！
I am sorry about not reading train.sh carefully.
But now, i could run the baseline on my pc ！！！

**Comment by luhua-rain** [comment]
> step 1: firstly have to convert session data to sample data by ./tools/convert_session_to_sample.py step 2: convert sample data to text data required by the model by ./tools/convert_conversation_corpus_to_model_text.py
> 
> The script run_train.sh/run_test.sh shows all the processes including data processing and model training/testing. Be sure to read it carefully and follow it.

Thank you for your reply！！！
I am sorry about not reading train.sh carefully.
But now, i could run the baseline on my pc ！！！
