### ISSUE TITLE
请问运行的时候sgns.weibo.300d.txt缺失，这个在哪下载啊？

### ISSUE THREAD

**Issue by shuiyuejihua** [baidu/knowledge-driven-dialogue#4]
stage 0
W0401 06:15:09.279657  8726 device_context.cc:263] Please NOTE: device: 0, CUDA Capability: 37, Driver API Version: 10.0, Runtime API Version: 9.0
W0401 06:15:09.279696  8726 device_context.cc:271] device: 0, cuDNN Version: 7.0.  
Building word embeddings from './data/sgns.weibo.300d.txt' ...  
('load init emb file failed', './data/sgns.weibo.300d.txt')  
Traceback (most recent call last):  
  File "network.py", line 529, in <module>  
    train(config)  
  File "network.py", line 499, in train  
    init_model(config, param_name_list, place)  
  File "network.py", line 220, in init_model  
    init_scale, np_t.shape)  
  File "/home/ubuntu/knowledge-driven-dialogue/generative_paddle/source/utils/utils.py", line 229, in init_embedding  
    raise Exception("load embedding file failed")

**Comment by imguozhen** [comment]
这是预训练词向量的文件，需要用自己的词向量文件替换。词向量文件格式如下：
格式：
![image](https://user-images.githubusercontent.com/6091232/55383349-906d2380-555a-11e9-80e4-b2deccf71ad3.png)
示例：
![image](https://user-images.githubusercontent.com/6091232/55383280-61ef4880-555a-11e9-8c77-e289d4f4c9aa.png)
